# Copyright 2026 Ali Sasanian
# SPDX-License-Identifier: Apache-2.0
"""
The backend contract, skeleton edition (v0.3 §8): put / get / query / tombstone / audit_append.
The backend returns candidates; the resolver applies precedence, trust and key-override.

This Protocol is the UNION the skeleton needed to run. The freeze splits it (Chief, 2026-09-21,
F3) into two contracts: ItemStore — put / get / query / tombstone, pluggable and delegable
(sqlite → postgres → mem0/zep) — and ContainerState — nodes, tokens, proposals and the audit
chain, sqlite by default, postgres at Phase 5, NEVER delegated to a third-party store. Blobs are
a third seam already: the blob store sits inside the store module (v0.5 §D, R5).
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator
from typing import Any, Protocol

from egzos.model import ContextItem, Node, Token


class Backend(Protocol):
    # nodes
    def put_node(self, node: Node) -> None: ...
    def get_node(self, node_id: str) -> Node | None: ...
    def list_nodes(self, parent: str | None = None, type: str | None = None) -> list[Node]: ...
    def find_root(self, type: str) -> Node | None: ...

    # items
    def put(self, item: ContextItem) -> None: ...
    def get(self, item_id: str) -> ContextItem | None: ...
    def query(
        self,
        scopes: Iterable[str],
        *,
        kinds: Iterable[str] | None = None,
        key: str | None = None,
        statuses: Iterable[str] | None = None,
        text: str | None = None,
        include_tombstoned: bool = False,
    ) -> list[ContextItem]: ...
    def tombstone(self, item_id: str) -> bool: ...

    # audit (append-only; the ledger computes the chain, the backend only appends)
    def audit_append(self, entry: dict[str, Any]) -> dict[str, Any]: ...
    def audit_last(self) -> dict[str, Any] | None: ...
    def audit_iter(self) -> Iterator[dict[str, Any]]: ...
    def audit_tail(self, n: int) -> list[dict[str, Any]]: ...

    # tokens
    def put_token(self, token: Token) -> None: ...
    def get_token(self, token_id: str) -> Token | None: ...
    def list_tokens(self) -> list[Token]: ...

    # pending proposals (cross-audience moves, staged artifacts)
    def put_proposal(self, proposal: dict[str, Any]) -> None: ...
    def get_proposal(self, proposal_id: str) -> dict[str, Any] | None: ...
    def list_proposals(self, status: str | None = None) -> list[dict[str, Any]]: ...
